/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package notreprojetjava;

import java.io.FileNotFoundException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACHAMBRI
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    static Entreprise entreprise;
    public Accueil() throws FileNotFoundException, ParseException {
        initComponents();
        entreprise = new Entreprise();
        
        TPane.setTitleAt(0, "Gestion des Missions");
        TPane.setTitleAt(1, "Gestion des Employés");
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Numéro");
        model.addColumn("Libellé");
        model.addColumn("Statut");
        for(Mission maMission : entreprise.getListeMissions()){
            model.addRow(new String[]{maMission.getId(),maMission.getLibelle(), maMission.colorStatut()});
        }   
        JTableMission.setModel(model);
        
        DefaultTableModel modelEmp = new DefaultTableModel();
        modelEmp.addColumn("Numéro");
        modelEmp.addColumn("Prénom");
        modelEmp.addColumn("Nom");
        for(Employe e : entreprise.getListeEmployes()){
            modelEmp.addRow(new String[]{e.getId(),e.getPrenom(), e.getNom()});
        }   
        jTableEmp.setModel(modelEmp);  
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TPane = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTableMission = new javax.swing.JTable(){
            public boolean isCellEditable(int d, int c){
                return false;
            }
        };
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmp = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel2.setText("GESTION DE L'ENTREPRISE");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Accueil");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setText("* Cliquez sur une mission ou un employé pour accéder aux détails correspondants");

        TPane.setToolTipText("");

        JTableMission.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numéro", "Libellé", "Statut"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        JTableMission.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTableMissionMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(JTableMission);
        if (JTableMission.getColumnModel().getColumnCount() > 0) {
            JTableMission.getColumnModel().getColumn(2).setPreferredWidth(2);
        }

        TPane.addTab("tab1", jScrollPane2);

        jTableEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableEmpMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEmp);

        TPane.addTab("tab2", jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(462, 462, 462))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4))
                            .addComponent(TPane, javax.swing.GroupLayout.PREFERRED_SIZE, 827, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TPane, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        TPane.getAccessibleContext().setAccessibleName("Missions");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTableMissionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTableMissionMousePressed
        // TODO add your handling code here:
        if(evt.getClickCount() == 2){
            JDetailMission frameDetailMission = null ;
            int Ligne = JTableMission.getSelectedRow();
            int colonne = 0;
            String codeMiss = (String) JTableMission.getValueAt(Ligne, colonne);
            //frameDetailMission = new JDetailMission(entreprise, entreprise.recupMissById(codeMiss));
            //frameDetailMission.setVisible(true);
            for(Mission maMission : entreprise.getListeMissions()){
                if(maMission.getId().equals(codeMiss)){
                    frameDetailMission = new JDetailMission(entreprise, maMission); 
                    frameDetailMission.setLocationRelativeTo(null);
                    frameDetailMission.setVisible(true);
                }
            }

        }
    }//GEN-LAST:event_JTableMissionMousePressed

    private void jTableEmpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEmpMousePressed
        if(evt.getClickCount() == 2){
            JDetailEmploye frameDetailEmploye = null ;
            int Ligne = jTableEmp.getSelectedRow();
            int colonne = 0;
            String codeEmp = (String) jTableEmp.getValueAt(Ligne, colonne);
            //frameDetailMission = new JDetailMission(entreprise, entreprise.recupMissById(codeMiss));
            //frameDetailMission.setVisible(true);
            for(Employe e : entreprise.getListeEmployes()){
                if(e.getId().equals(codeEmp)){
                    frameDetailEmploye = new JDetailEmploye(entreprise, e);
                    frameDetailEmploye.setLocationRelativeTo(null);
                    frameDetailEmploye.setVisible(true);
                }
            }

        }
    }//GEN-LAST:event_jTableEmpMousePressed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Accueil().setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ParseException ex) {
                    Logger.getLogger(Accueil.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTableMission;
    private javax.swing.JTabbedPane TPane;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableEmp;
    // End of variables declaration//GEN-END:variables
}
