/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package notreprojetjava;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import static notreprojetjava.AjoutMission.entreprise;
import static notreprojetjava.JDetailEmploye.monEmp;

/**
 *
 * @author achambri
 */
public class AjoutEmploye extends javax.swing.JFrame {

    /**
     * Creates new form AjoutEmploye
     */
    static Entreprise entreprise;
    public AjoutEmploye(Entreprise entreprise) {
        this.entreprise = entreprise ;
        initComponents();
        
        //Gestion des Competences
        DefaultTableModel modelCompEmploye = new DefaultTableModel();
        modelCompEmploye.addColumn("id");
        modelCompEmploye.addColumn("libelle");
        JTCompEmp.setModel(modelCompEmploye);
        
        DefaultTableModel modelLesComp = new DefaultTableModel();
        modelLesComp.addColumn("id");
        modelLesComp.addColumn("libelle");
        for(Competence maCompetencesCSV : entreprise.getListeCompetences()){
            modelLesComp.addRow(new String[]{maCompetencesCSV.getId(), maCompetencesCSV.getLibelleFR()});
        }
        JTLesComp.setModel(modelLesComp);
        TableColumnModel tcm = JTLesComp.getColumnModel();
        tcm.getColumn(0).setPreferredWidth(10);
        tcm.getColumn(1).setPreferredWidth(250);
        
        erreur.setEditable(false);
        
        this.setResizable(false);
        
        this.setDefaultCloseOperation(2);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomEmp = new javax.swing.JTextField();
        prenomEmp = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateJ = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dateM = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dateA = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        JTCompEmp = new javax.swing.JTable();
        JTAjoutComp = new javax.swing.JButton();
        JTRemoveComp = new javax.swing.JButton();
        BTNRetour = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTLesComp = new javax.swing.JTable();
        BTNAjout = new javax.swing.JButton();
        message = new javax.swing.JScrollPane();
        erreur = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel13.setText("Ajouter un employé :");

        jLabel1.setText("Nom :");

        jLabel2.setText("Prenom :");

        jLabel4.setText("Date entrée :");

        jLabel5.setText("/");

        jLabel6.setText("/");

        JTCompEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTCompEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTCompEmpMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(JTCompEmp);

        JTAjoutComp.setText("Ajouter >>");
        JTAjoutComp.setEnabled(false);
        JTAjoutComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTAjoutCompActionPerformed(evt);
            }
        });

        JTRemoveComp.setText("<< Supprimer");
        JTRemoveComp.setEnabled(false);
        JTRemoveComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTRemoveCompActionPerformed(evt);
            }
        });

        BTNRetour.setBackground(new java.awt.Color(239, 131, 131));
        BTNRetour.setText("Retour");
        BTNRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNRetourActionPerformed(evt);
            }
        });

        jLabel7.setText("Les Compétences :");

        JTLesComp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JTLesComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JTLesCompMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(JTLesComp);

        BTNAjout.setBackground(new java.awt.Color(132, 204, 132));
        BTNAjout.setText("Ajouter");
        BTNAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAjoutActionPerformed(evt);
            }
        });

        erreur.setColumns(20);
        erreur.setRows(5);
        message.setViewportView(erreur);

        jLabel8.setText("Les Compétences de l'employé:");

        jLabel9.setText("Message :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 67, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JTRemoveComp)
                            .addComponent(JTAjoutComp, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNRetour)
                        .addGap(18, 18, 18)
                        .addComponent(BTNAjout)
                        .addContainerGap(338, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomEmp)
                            .addComponent(prenomEmp)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(dateJ, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nomEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(prenomEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dateM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(dateJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTAjoutComp)
                        .addGap(40, 40, 40)
                        .addComponent(JTRemoveComp)
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNRetour)
                            .addComponent(BTNAjout))
                        .addGap(75, 75, 75))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(message, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTCompEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTCompEmpMouseClicked
        JTRemoveComp.setEnabled(true);
    }//GEN-LAST:event_JTCompEmpMouseClicked

    private void JTAjoutCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTAjoutCompActionPerformed
        // TODO add your handling code here:
        int ligne = JTLesComp.getSelectedRow();
        int colonneId = 0 ;
        int colonneNomFra = 1;
        String id = (String) JTLesComp.getValueAt(ligne, colonneId);
        String nomFra = (String) JTLesComp.getValueAt(ligne, colonneNomFra);

        DefaultTableModel modelLesCompEmp =(DefaultTableModel)  JTCompEmp.getModel();
        modelLesCompEmp.addRow(new Object[]{id,nomFra});
        JTCompEmp.setModel(modelLesCompEmp);

        //Enlever la compétence de la Jtable

        DefaultTableModel modelLesComp =(DefaultTableModel)  JTLesComp.getModel();
        modelLesComp.removeRow(ligne);
        JTLesComp.setModel(modelLesComp);
        Competence uneComp = entreprise.recupCompById(id);
        JTAjoutComp.setEnabled(false);
    }//GEN-LAST:event_JTAjoutCompActionPerformed

    private void JTRemoveCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTRemoveCompActionPerformed
        // TODO add your handling code here:
        int ligne = JTCompEmp.getSelectedRow();
        int colonneId = 0 ;
        int colonneNomFra = 1;
        String id = (String) JTCompEmp.getValueAt(ligne, colonneId);
        String nomFra = (String) JTCompEmp.getValueAt(ligne, colonneNomFra);

        DefaultTableModel modelLesCompEmp =(DefaultTableModel)  JTCompEmp.getModel();
        modelLesCompEmp.removeRow(ligne);
        JTCompEmp.setModel(modelLesCompEmp);

        DefaultTableModel modelLesComp =(DefaultTableModel)  JTLesComp.getModel();
        modelLesComp.addRow(new Object[]{id,nomFra});
        JTLesComp.setModel(modelLesComp);

        Competence uneComp = entreprise.recupCompById(id);
        JTRemoveComp.setEnabled(false);
    }//GEN-LAST:event_JTRemoveCompActionPerformed

    private void BTNRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNRetourActionPerformed
        this.dispose();
    }//GEN-LAST:event_BTNRetourActionPerformed

    private void JTLesCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTLesCompMouseClicked
        JTAjoutComp.setEnabled(true);
    }//GEN-LAST:event_JTLesCompMouseClicked

    private void BTNAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAjoutActionPerformed
        String erreurMessage = "" ;
        String newLine = System.getProperty("line.separator");
        if(nomEmp.getText().equals("")){
            erreurMessage += "veuillez entrer un Nom" + newLine;
        }
        if(prenomEmp.getText().equals("")){
            erreurMessage += "veuillez entrer un prenom" + newLine;
        }
        if(dateA.getText().equals("")){
            erreurMessage += "veuillez entrer l'année d'entrée de l'employé" + newLine;
        }
        if(dateM.getText().equals("")){
            erreurMessage += "veuillez entrer le mois d'entrée de l'employé" + newLine;
        }
        if(dateJ.getText().equals("")){
            erreurMessage += "veuillez entrer le jour d'entrée de l'employé" + newLine;
        }

        if(erreurMessage != ""){
            erreur.setText(erreurMessage);
        } 
        else {
            String date = "" ;
            date += dateJ.getText() + "/";
            date += dateM.getText() + "/";
            date += dateA.getText();


            
            try {
                String idEmp = "";
                idEmp = entreprise.creerEmp(nomEmp.getText(), prenomEmp.getText(), date);
                int nbCompte = JTCompEmp.getRowCount();
                System.out.println("BONJOUR");
                System.out.println(nbCompte);
                if(nbCompte > 0){    
                    for (int i = 0; i < nbCompte; i++) {
                        System.out.println("BONJOUR MONSIEUR ");
                        String idComp = (String)JTCompEmp.getValueAt(i, 0);
                        entreprise.addCompEmp(entreprise.recupEmpById(idEmp), entreprise.recupCompById(idComp));
                    }
                }
                entreprise.saveEmp();
                nomEmp.setText("");
                prenomEmp.setText("");
                dateA.setText("");
                dateJ.setText("");
                dateM.setText("");
                erreur.setText("Employé ajouté");
                
                //Gestion des Competences
                DefaultTableModel modelCompEmploye = new DefaultTableModel();
                modelCompEmploye.addColumn("id");
                modelCompEmploye.addColumn("libelle");
                JTCompEmp.setModel(modelCompEmploye);

                DefaultTableModel modelLesComp = new DefaultTableModel();
                modelLesComp.addColumn("id");
                modelLesComp.addColumn("libelle");
                for(Competence maCompetencesCSV : entreprise.getListeCompetences()){
                    modelLesComp.addRow(new String[]{maCompetencesCSV.getId(), maCompetencesCSV.getLibelleFR()});
                }
                JTLesComp.setModel(modelLesComp);
                erreur.setEditable(false);

            } catch (FileNotFoundException ex) {
                Logger.getLogger(AjoutEmploye.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(AjoutEmploye.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(AjoutEmploye.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_BTNAjoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjoutEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjoutEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjoutEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjoutEmploye.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
//            public void run() {
//                new AjoutEmploye().setVisible(true);
//            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAjout;
    private javax.swing.JButton BTNRetour;
    private javax.swing.JButton JTAjoutComp;
    private javax.swing.JTable JTCompEmp;
    private javax.swing.JTable JTLesComp;
    private javax.swing.JButton JTRemoveComp;
    private javax.swing.JTextField dateA;
    private javax.swing.JTextField dateJ;
    private javax.swing.JTextField dateM;
    private javax.swing.JTextArea erreur;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane message;
    private javax.swing.JTextField nomEmp;
    private javax.swing.JTextField prenomEmp;
    // End of variables declaration//GEN-END:variables
}
